---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 0e3afd419a0996cf0c80a05a983c498c3ca6902c
    app.quarkus.io/build-timestamp: 2023-03-06 - 23:51:41 +0000
  labels:
    app.kubernetes.io/name: aberdrei
    app.kubernetes.io/version: "1"
  name: aberdrei
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: aberdrei
      app.kubernetes.io/version: "1"
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 0e3afd419a0996cf0c80a05a983c498c3ca6902c
        app.quarkus.io/build-timestamp: 2023-03-06 - 23:51:41 +0000
      labels:
        app.kubernetes.io/name: aberdrei
        app.kubernetes.io/version: "1"
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: wunderwebt/aberdrei:1
          imagePullPolicy: Always
          name: aberdrei
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 0e3afd419a0996cf0c80a05a983c498c3ca6902c
    app.quarkus.io/build-timestamp: 2023-03-06 - 23:51:41 +0000
  labels:
    app.kubernetes.io/name: aberdrei
    app.kubernetes.io/version: "1"
  name: aberdrei
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: aberdrei
    app.kubernetes.io/version: "1"
  type: ClusterIP
