AberGym PlantUML ERD

@startuml
' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho


entity "Person" as person {
  *Id : number <<generated>>
  --
  name : text
  birth_date : date
  high : number
  weight : number
  gender : text
}

entity "Trainee" as trainee {
  *customer_id : number <<generated>>
  --
  name : text
  trainingspaln : text
  birthdate : date
  phone_number : text
  email : text
  start_date : date
}

entity "Trainer" as trainer {
  *Trainer_id : number <<generated>>
  --
  name : text
  birthdate : date
  phone_number : text
  email : text
  gender : text
  templates : text
}

entity "Template" as template {
  *template_id : number <<generated>>
  --
  trainer_id : number
  name : text
  aim : text
  level : text
  exercises : list(exercise)
}

entity "Exercise" as exercise {
  *exercise_id : number <<generated>>
  --
  name : text
  aim : text
  note : text
  weight : number
  reps : number
  time : number
  excercise_type : string
  description : text
}

entity "Split" as t_plan {
  *plan_id : number <<generated>>
  --
  name : text
  Trainee_id : number
  exercises : list(exercise)
}

entity "Muscle_Group" as e_group{
   *plan_id : number <<generated>>
   --
   name : text
   body_part : text
}

entity "Studio" as studio{
   *Studio_id : number <<generated>>
   --
   name : text
   adresse : text
   city : text
   country : text
   postalcode : number
}
studio }|--|{ trainee
studio --|{ trainer
person .. trainee
person .. trainer
trainer --|{ template
trainee --|{ t_plan
template --|{ exercise

exercise --|{ e_group
t_plan --|{ exercise

@enduml
